import 'package:get/get_navigation/src/root/internacionalization.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "app_name": "Bhade Taxi",
      "enter_mobile" : 'Enter Your mobile number',
      'we_send_you' : 'We\'ll send you a ',
      '4_digit_otp' : '4 digit OTP',
      'on_your_mobile_number' : 'on your mobile number for verification',
      'pls_enter_valid_mobile_number' : 'Please enter valid mobile number',
      'enter_10_digit_mobile_number' : 'Enter 10 digit mobile number',
      'mobile_number' : 'Mobile Number',
      'don\'t_worry' : 'Don\'t worry your number will not be shared with anyone',
      'internet_connection_problem' : 'Internet Connection not available',
      'get_otp' : 'GET OTP',
      'enter_code' : 'Enter Code',
      'invalid_otp' : 'Invalid OTP',
      'pls_enter_otp' : 'Please enter complete OTP',
      'verify' : 'VERIFY',
      'verify_mobile_number' : 'Verify Mobile Number',
      'verification_sent' : 'Verification Code sent to your mobile number',
      'hello' : 'Hello,',
      'customer' : 'Customer',
      'vendor' : 'Vendor',
      'vehicle' : 'Vehicle',
      'profile' : 'Profile',
      'add_booking' : 'Add Booking',
      'payment_pending' : 'Payment Pending',
      'upcoming_booking' : 'Upcoming Booking',
      'complete_transaction' : 'Complete Transaction',
      'no' : 'No :',
      'payment' : 'Payment',
      'to' : 'To',
      'days' : 'Days',
      'booked_by' : 'Booked by: ',
      'deleted_by':'Deleted by: ',
      'are_you_sure_to_delete_this_booking' : 'Are You sure to delete this Booking?',
      'no1' : 'NO',
      'yes_delete_booking' : 'YES,DELETE BOOKING',
      'do_you_want_to_exit_from_this_app' : 'Do you want to exit from this app ?',
      'yes' : 'Yes',
      'phone_permission_is_required_to_make_calls' : 'Phone permission is required to make calls.',
      'booking_form' : 'Booking Form',
      'customer_detail' : 'Customer Detail',
      'date' : 'Date',
      'time' : 'Time',
      'customer_name' : 'Customer Name',
      'pls_enter_customer_name' : 'Please enter customer name',
      'add_from_contact_book' : '+ Add from Contact Book',
      'pls_enter_mobile_number' : 'Please enter Mobile number',
      'trip_type' : 'Trip Type',
      'pls_enter_trip_type' : 'Please enter trip type',
      'pickup' : 'Pickup',
      'pls_enter_pick_up_location_name' : 'Please enter Pick up location name',
      'drop' : 'Drop',
      'pls_enter_drop_location_name' : 'Please enter Drop location name',
      'no_of_days' : 'No of Days',
      'pls_enter_number_of_days' : 'Please enter number of days',
      'car_type' : 'Car Type',
      'pls_enter_car_type' : 'Please enter car type',
      'car_name' : 'Car Name',
      'pls_enter_car_name' : 'Please enter car name',
      'amount' : 'Amount',
      'pls_enter_amount' : 'Please enter amount',
      'booking_add_by' : 'Booking Add By',
      'remarks' : 'Remarks',
      'vendor_and_driver_details' : 'Vendor & Driver details',
      'vendor_name' : 'Vendor Name',
      'pls_enter_vendor_name' : 'Please enter Vendor name',
      'vendor_mobile_no' : 'Vendor Mobile No.',
      'pls_enter_vendor_mobile_number' : 'Please enter Vendor Mobile number',
      'car_number' : 'Car Number',
      'pls_enter_car_number' : 'Please enter car number',
      'vendor_amount' : 'Vendor Amount',
      'pls_enter_vendor_amount' : 'Please enter vendor amount',
      'profit_amount' : 'Profit Amount',
      'pls_enter_profit_amount' : 'Please enter profit amount',
      'driver_name' : 'Driver Name',
      'pls_enter_driver_name' : 'Please enter Driver name',
      'driver_mobile_no' : 'Driver Mobile No.',
      'pls_enter_driver_mobile_number' : 'Please enter driver Mobile number',
      'update' : 'UPDATE',
      'book_now' : 'BOOK NOW',
      'pls_select_date' : 'Please select date',
      'pls_select_time' : 'Please select time',
      'pls_enter_customer_phone_number' : 'Please enter customer phone number',
      'pls_enter_source_address' : 'Please enter source address',
      'pls_enter_destination_address' : 'Please enter destination address',
      'pls_enter_valid_profit_amount' : 'Please enter valid profit amount',
      'pls_enter_driver_phone_number' : 'Please enter driver phone number'

    },

    'hi_IN': {
      "app_name": "ग्रोसरी",
    },

    'gu_IN': {
      "app_name": "ગ્રોસરી",
    },
  };
}